name: Waka Readme

on:
  schedule:
    # Run start everyday on 05:00AM GMT-3
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Atualizando readme com métricas do wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          IGNORED_REPOS: "projeto-fullstack-dsmovie--, lastfm-recentemente-reproduzidas-readme, github-readme-streak-stats, waka-readme-stats, github-readme-stats"
          COMMIT_MESSAGE: "Atualizado estatisticas do perfil :heart:"
          LOCALE: "pt-BR"
          SYMBOL_VERSION: "2"
