name: Waka Readme

on:
  schedule:
    # Run start everyday on 05:00AM GMT-3
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Atualizando README com Métricas Wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: c-viniciussantos/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          COMMIT_MESSAGE: "Atualizado Stats do Perfil! :heart:"
          LOCALE: "pt-BR"
          SYMBOL_VERSION: "2"
