name: Waka Readme

on:
  schedule:
    # Runs everyday on 05:00AM GMT-3
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: c-viniciussantos/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_UPDATED_DATE: "True"
          IGNORED_REPOS: "c-viniciussantos"
          COMMIT_MESSAGE: "Atualizando Stats do Perfil! :thinking: :hand_over_mouth: :partying_face: :heart: :technologist:"
          LOCALE: "pt-BR"
          SYMBOL_VERSION: "2"
